### ISSUE TITLE
Running OMPL as a pre-processor for STOMP doesn't work.

### ISSUE THREAD

**Issue by luckychay** [ros-planning/panda_moveit_config#53] opened 2020-02-17 02:43 UTC
I'm following the Planning Adapter Tutorials of Moveit! at [http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/planning_adapters/planning_adapters_tutorial.html](url), but I can't implement the Running OMPL as a pre-processor for STOMP. Although I installed stomp_core from source which origined from [https://github.com/ros-industrial/stomp_ros](url),  I got an  error like this:
`[ERROR] [1581905685.671780997]: Exception while loading planning adapter plugin 'stomp/SmoothingAdapter': According to the loaded plugin descriptions the class stomp/SmoothingAdapter with base class type planning_request_adapter::PlanningRequestAdapter does not exist. Declared types are  chomp/OptimizerAdapter default_planner_request_adapters/AddIterativeSplineParameterization default_planner_request_adapters/AddTimeOptimalParameterization default_planner_request_adapters/AddTimeParameterization default_planner_request_adapters/Empty default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/FixStartStatePathConstraints default_planner_request_adapters/FixWorkspaceBounds default_planner_request_adapters/ResolveConstraintFrames industrial_trajectory_filters/AddSmoothingFilter industrial_trajectory_filters/NPointFilter industrial_trajectory_filters/UniformSampleFilter
`
Is there anyone who has run the demo successfully or anyone who can tell me how to solve this problem?

**Comment by rhaschke** [comment] 2020-02-17 07:17
Duplicate of https://github.com/ros-planning/moveit_tutorials/issues/453.

**Closed as completed by rhaschke** 2020-02-17 07:17 UTC
